apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flag-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/NyEstevo/fiap-tech-challenges.git
    targetRevision: main
    path: fase-3/gitops/manifests/flag
  destination:
    server: https://kubernetes.default.svc
    namespace: toggle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
