apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # sincroniza antes dos apps de servico -> o ClusterSecretStore existe
    # quando os ExternalSecrets de cada servico forem reconciliados
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/NyEstevo/fiap-tech-challenges.git
    targetRevision: lab
    path: fase-3/gitops/manifests/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
