apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: targeting-secret
  namespace: targeting
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpMME5xOGY0cUdkSU5SVDdMRVNMekB0Yy1yZHMtdGFyZ2V0aW5nLmM5MHFxbWc2YWFzZC51cy1lYXN0LTIucmRzLmFtYXpvbmF3cy5jb206NTQzMi90YXJnZXRpbmdfZGI=