apiVersion: v1
kind: Service
metadata:
  name: targeting-service-svc
  namespace: tech-challenge-fase-2
  labels:
    app: targeting-service
spec:
  selector:
    app: targeting-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
  type: ClusterIP