apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toggle-master-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/NyEstevo/fiap-tech-challenges.git
    targetRevision: lab
    path: fase-3/gitops/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
