apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: tech-challenge-fase-2
data:
  EVALUATION_INTERVAL: "60"
  PORT: "8004"
  AWS_REGION: "us-east-1"
  REDIS_URL: "rediss://evaluation-service-2-bszzdn.serverless.use1.cache.amazonaws.com:6379"
  FLAG_SERVICE_URL: "http://flags-service-svc"
  TARGETING_SERVICE_URL: "http://targeting-service-svc"
  AUTH_SERVICE_URL: "http://auth-service-svc"
  ANALYTICS_SERVICE_URL: "http://analytics-service-svc"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/506394430088/analytics-service-queue"
  # REDIS_TLS_INSECURE: "true"
