apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: evaluation-secret
  namespace: toggle
type: Opaque
data:
  SERVICE_API_KEY: dG1fa2V5X2JhODYxZWJiZjc2ZWEwYmM5ZWRmNjlhYTRjYzVlMzkxYWExNTEzNjcyYmY1MjFiOWE1OTkzMTQzOGM1N2NhOTA=
