apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: analytics-secret
  namespace: toggle
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: analytics-secret # adicionado ao envFrom via patch no kustomization
    creationPolicy: Owner
  data:
    # analytics nao tem segredo; sao valores de config derivados da infra
    - secretKey: AWS_SQS_URL
      remoteRef: { key: tc-analytics-app, property: AWS_SQS_URL }
    - secretKey: AWS_DYNAMODB_TABLE
      remoteRef: { key: tc-analytics-app, property: AWS_DYNAMODB_TABLE }
    - secretKey: AWS_REGION
      remoteRef: { key: tc-analytics-app, property: AWS_REGION }
