apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # sem bloco 'auth': o ESO usa a cadeia de credenciais padrao da AWS
      # (IMDS do node -> LabRole do Academy). Sem IRSA. A LabRole ja permite
      # secretsmanager:GetSecretValue.
