apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flags-service-hpa
  namespace: tech-challenge-fase-2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flags-service-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
