apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: flag-secret
  namespace: toggle
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpxSlZ3UlVGUTd0UXZBd2ExcWI4RkB0Yy1yZHMtZmxhZy5jOTBxcW1nNmFhc2QudXMtZWFzdC0yLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvZmxhZ3NfZGI=