apiVersion: v1
kind: Service
metadata:
  name: flags-service-svc
  namespace: tech-challenge-fase-2
  labels:
    app: flags-service
spec:
  selector:
    app: flags-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: ClusterIP
  